version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@1.2.0

filters:
  branches:
    only: /v0\.1_24\.*/

jobs:
  compiler-build:
    executor: python/default
    working_directory: ~/project/compiler
    steps:
      - checkout
      - python/install-packages:
          app-dir: ~/project/compiler
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            pytest --version
          name: Ping

  # need to find a linux / .net core setup o
  runner-build:
     executor: win/default 
     working_directory: ~/project/runner 
     steps:
       - run:
          command: pwd
          name: wtfaw
       - checkout
       - run: dotnet build

workflows:
  # compiler:
  #   jobs:
  #     - compiler
  all:
    jobs:
    - python/test:
        app-dir: ~/project/compiler
        pip-dependency-file: requirements.txt
        pkg-manager: pip
        test-tool: pytest
    - runner-build
