version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@0.2.1

filters:
  branches:
    only: /v0\.1_24\.*/

jobs:
  compiler:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: echo "hello world"
          name: Stub
  
  runtime:
     executor: win/default     
     steps:
       - run:
          command: echo "hello world"
          name: Stub
       - checkout
       - run: dotnet build

workflows:
  # compiler:
  #   jobs:
  #     - compiler
  all:
    jobs:
    - compiler
    - runtime
