version: 2.1

orbs:
  ### Orbs are basically libraries
  python: circleci/python@1.2.0

### Use branch filter when testing changes to this file
filters:
  branches:
    only: /v0\.1\/114*/

### TODO: Unit tests from Makefile, over project Docker image.

jobs:
 
  test-compiler:
    ### Cannot use predefined python/test does not let you run the tests in a subdirectory.
    executor: python/default
    steps:
      - checkout
      - run:
          name: Test Compiler
          working_directory: ~/project/compiler
          command: |
            pip3 install -r test/test_requirements.txt
            mkdir test-report
            pytest --junit-xml=test-report/report.xml test

  ### TODO: Define dev and CI images in one file.
  test-runner:
    docker:
      - image: philallen117/nutmeg-circleci
        auth:
          username: philallen117
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: 
          name: Test Runner
          working_directory: ~/project/runner
          command: |
            dotnet build
            dotnet test

  inttests:
    docker:
      - image: philallen117/nutmeg-circleci
        auth:
          username: philallen117
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: 
          name: Integration tests
          working_directory: ~/project
          command: |
            make build
            make install
            make inttests
  

### Can worflows be scoped by folder? Or maybe by pattern on branch name?
workflows:
  all:
    jobs:
    - test-compiler
    - test-runner
    - inttests
